// Generated by CoffeeScript 1.3.3

/*
Module dependencies.
*/


(function() {
  var app, conf, express, http, logger, nodemailer, transport;

  express = require("express");

  nodemailer = require("nodemailer");

  http = require("http");

  conf = require("./conf/conf.js");

  app = express();

  transport = nodemailer.createTransport("SMTP", conf.mail);

  logger = console;

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  app.configure("development", function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure("production", function() {
    return app.use(express.errorHandler());
  });

  app.post("/", function(req, res) {
    var bod, mail;
    bod = req.body;
    if (conf.whitelist.indexOf(bod.to) < 0) {
      return res.send(500);
    }
    mail = {
      from: bod.from.replace('@', '\\@'),
      replyTo: bod.from,
      to: bod.to,
      subject: bod.subject,
      text: bod.text
    };
    return transport.sendMail(mail, function(error, response) {
      if (error) {
        res.send(500);
        logger.error(error);
        return;
      }
      if (!bod.redir) {
        res.send(200);
      }
      if (bod.redir) {
        return res.redirect(bod.redir);
      }
    });
  });

  app.get("/test", function(req, res) {
    var resp;
    resp = "<html><body><form action='/' method='post'><input type='text' name='from'><input type='text' name='to'><input type='text' name='subject'><input type='text' name='text'><input type='submit'></form></body></html>";
    return res.send(resp);
  });

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
